### ISSUE TITLE
FeaturesAction do not consider LicenseFeature

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#103]
Tycho currently has a more or less [fork of FeaturesAction](https://github.com/eclipse/tycho/blob/master/tycho-bundles/org.eclipse.tycho.p2.resolver.impl/src/main/java/org/eclipse/tycho/p2/impl/publisher/FeatureDependenciesAction.java) because the P2 provided one do not consider LicenseFeature.

Even though one might argue a LicenseFeature could be seen optional, it might be good to at least create an optional dependency to it. Also it is a workaround for https://github.com/eclipse-equinox/p2/issues/101

**Comment by merks** [comment]
The other issue mentions making some method protected.   This issue doesn't actually describe any action that I understand.  As I understand it, we don't need a dependency on a/the license feature because everything is copied during the build.  What will an optional dependency buy us?  Unless there is a non-optional or at least a greedy dependency, it wouldn't be installed anyway, so what is the goal/purpose here?

**Comment by mickaelistria** [comment]
The license feature used to be merged into the "host" feature at build time, not making it a dependency. Has it changed? Maybe Tycho shouldn't just create a requirement if the content is copied already.

**Comment by laeubi** [comment]
I'm not sure what "has changed" refers to, currently the (P2) `FeatureAction` simply ignores license-feature, that means you end with an IU that only references the feature (and maybe its included bundles and features). Because of this Tycho includes `FeatureDependenciesAction` what adds a requirement for this and lots of code "some time in the past" copied form `FeatureAction`

https://github.com/eclipse/tycho/blob/bb190b4f39df1a55012b89f45ee9adba31a9f70a/tycho-bundles/org.eclipse.tycho.p2.resolver.impl/src/main/java/org/eclipse/tycho/p2/impl/publisher/FeatureDependenciesAction.java#L100-L105

So my goal/plan would be to enhance `FeatureAction` by either always adding (whatever is suitable) requirement, or have a setting I can pass to do so, so we don't need to maintain a copy in Tycho (what most probably will get out of sync some time).

**Comment by mickaelistria** [comment]
The question stands: does the LicenseFeature has to be a requirement? Does the "host" feature need to reference the license feature in general? The way it used to be built was that content was copied into the jar, it was not a requirement at install time so p2 could ignore it when generating metadata or installing.
So if there is no install-time/build-time requirement from host to license feature, then p2 is correct in not creating an extra reference.

**Comment by laeubi** [comment]
> The question stands: does the LicenseFeature has to be a requirement?

At least for Tycho, yes there is even an integration test that covers this, because the license feature must be build before any feature using it.

**Comment by mickaelistria** [comment]
It's more a build requirement than a general install requirement then. In such case, it does make sense that this is covered only in Tycho.

**Comment by merks** [comment]
Yes, that's my concern.  This happens with Oomph as well that we want it at development time, but generating a requirement to it in p2's published metadata seems wrong.

**Comment by laeubi** [comment]
What about a method `requireLicenseFeature` to enable/disable this?

**Comment by merks** [comment]
Something to conditionally enable that sounds like a good idea.  

We have this in Oomph which adds the license feature as a requirement for development time dependencies:

https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/tree/plugins/org.eclipse.oomph.targlets/src/org/eclipse/oomph/targlets/impl/FeatureGeneratorImpl.java#n132
https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/tree/plugins/org.eclipse.oomph.targlets/src/org/eclipse/oomph/targlets/impl/FeatureGeneratorImpl.java#n161

Here you will also see AdviceFileAdvice in action too and understand why I'd not be happy to see breakage.

**Comment by laeubi** [comment]
Closing this as not being relevant anymore (for me) as it seems more profitable to get rid of outdated P2 technology in Tycho and moving on to more modern and flexible approaches:
- https://github.com/eclipse-tycho/tycho/issues/2019
