### ISSUE TITLE
Eclipse 202206 mirrors located in Russia ( javax.net.ssl.SSLHandshakeException: PKIX path building failed)

### ISSUE THREAD

**Issue by microwan** [eclipse-equinox/p2#106]
Dear all ,

i do not know if it is the right place to post.
I am using a target platform with oomph to install a development environment based on customed 202206 Target Platform
I am facing a strange error.
https://mirror.tspu.ru/eclipse/releases/2022-06/202206151000/plugins/

 ERROR: org.eclipse.equinox.p2.artifact.repository code=13 Retry another mirror
      ERROR: org.eclipse.equinox.p2.transport.ecf code=1002 Unable to read repository at https://mirror.tspu.ru/eclipse/releases/2022-06/202206151000/plugins/org.eclipse.ui_3.201.0.v20220124-1108.jar.
      javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    
my cacerts is correct.

                Best Regards

                                      Erwan

**Comment by merks** [comment]
You can use -Declipse.p2.mirrors=false to disable mirrors; add it to end of the eclipse.ini.  (The installer, in advanced mode, has a checkbox on the Confirmation page to toggle this during installation.)  I assume that will avoid the problem.

Which Java version is being used here?  Are you inside a corporate firewall?

**Comment by merks** [comment]
I'll assume that addresses the issue.
