### ISSUE TITLE
Allow trusting artifacts by PGP even if jarsigned

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-equinox/p2#121]
Currently, PGP seems ignored if an artifact has jarsigner. However, in some cases (eg BouncyCastle), the signing certificate can hardly be trusted by default and we want to have PGP signature used as a base for trust.
So the Trust strategy, assuming the verification strategy honors PGP in that case, should try to trust PGP equally as jarsign-ing info.

**Comment by merks** [comment]
Just to confirm, but I think I can create a test case (p2 repository) using this configured to be false, right?

https://www.eclipse.org/tycho/sitedocs/tycho-gpg-plugin/sign-p2-artifacts-mojo.html#skipIfJarsigned

Does Tycho need some more fine-grained way to specify this the desire for a PGP signature for specific artifacts in the future?

**Comment by mickaelistria** [comment]
Right, `skipIfJarsigned=false` should easily allow to have both forms of signatures on a set of artifact.

> Does Tycho need some more fine-grained way to specify this the desire for a PGP signature for specific artifacts in the future?

Yes, I think so.

**Comment by laeubi** [comment]
Why not keep it simple and just ad PGP to *every* artifact?

**Comment by mickaelistria** [comment]
> Why not keep it simple and just ad PGP to every artifact?

It grows too much the size of artifacts.jar.

**Comment by laeubi** [comment]
> It grows too much the size of artifacts.jar.

That's really funny, last time I said it would be good not to include it, it was argued it is that small in size that it doesn't matter at all and now we are finding workarounds because it "grows too much"?

**Comment by mickaelistria** [comment]
> That's really funny, last time I said it would be good not to include it, it was argued it is that small in size that it doesn't matter at all and now we are finding workarounds because it "grows too much"?

It's a small size for few artifacts, and the size that is added in artifacts.xml metadata is balanced by the lower size of the artifact which in turn doesn't include signature info.
But for Simrel with several thousands of artifacts, it doesn't scale; and as we already have jarsigning, it doesn't bring more value but would also require more CPU to verify 2 signatures instead of just 1.

**Comment by laeubi** [comment]
> But for Simrel with several thousands of artifacts, it doesn't scale;

That's why I said from day one that embedding signatures in the P2 xml will not scale and is a bad idea, I even repeated my concerns when it was decided to include the public key in each and every artifact **again** but also there it was argued it so small that it doesn't matter...

> it doesn't bring more value but would also require more CPU to verify 2 signatures instead of just 1.

No one forces you to verify *both*, we do not verify md5+sha1 if they are present but there is a delegation / preference order instead...

**Comment by laeubi** [comment]
Beside that I understand your request that P2 should accept if one is "good", this seems not a good choice here, as it allows to target the weakest vector here if P2 simply would trust *anything* if some are failing....

**Comment by mickaelistria** [comment]
> That's why I said from day one that embedding signatures in the P2 xml will not scale and is a bad idea, I even repeated my concerns when it was decided to include the public key in each and every artifact again but also there it was argued it so small that it doesn't matter...

Indeed, some things are not optimal and could still be improved. Help to improve that is welcome.
"Doesn't matter" is contextual: it depends on the current goals, requirements, constraints, deadlines... So what didn't matter 6 months ago may matter more today or tomorrow.

> No one forces you to verify both, we do not verify md5+sha1 if they are both present but there is a delegation / preference order instead...

If we want to be able to use both signature (or one or the other) in order to determine trust later on, then we need to verify that signature are actually matching the artifact. If we don't verify that signature match the artifact, then they become extremely unreliable and this is a potential vector attack to use them later on.

> Beside that I understand your request that P2 should accept if one is "good", this seems not a good choice here, as it allows to target the weakest vector here if P2 simply would trust anything if some are failing....

Let's be very precise here, because "good" can have too many meanings.
p2 allows installation if all signatures are *verified* (no incorrect signature) and if at least 1 signature/signer is *trusted*. It's already how things are working I believe, the only current issue is about trust: jarsignature do "disable" PGP-based trust and that is now undesired.

**Comment by laeubi** [comment]
> Indeed, some things are not optimal and could still be improved. Help to improve that is welcome.

Last time there where so much "don't change it" pressure that contributions do not seem valuable. Given that the PGP mojo [already outputs the asc files](https://github.com/eclipse/tycho/issues/872), it might be good to evaluate if checking for a side-by-side ASC file would be a solution here.

> p2 allows installation if all signatures are _verified_ (no incorrect signature) and if at least 1 signature/signer is _trusted_.

Is it really that way or is it that I either trust the certificate itself or anyone up in the chain? What if I explicitly *not* trust (e.g. rejected) one in the chain?

**Comment by merks** [comment]
@mickaelistria I'm making good progress...

I've created a local repository where I signed all the artifacts with my own local PGP key.  When installing the bouncycastle artifacts of that repo, this prompt now comes up:

![image](https://user-images.githubusercontent.com/208716/181723949-f6de5844-cdd6-4ec5-94d0-4a7bf881b049.png)

So you (the user) can see that there is an x509 certificate that has been used to jar-sign the two artifacts.

In addition, you (the user) can see that there is also a PGP signature on both the artifacts (that is my local PGP key):

![image](https://user-images.githubusercontent.com/208716/181724263-46ab5cc6-3e7b-4b5f-aa61-a5690e25200c.png)

One can choose to trust either or both of these two to complete the installation.

I think this meets the requirements/goal of this issue, right?  I still need to test cases such as when one or the other of these two choices is already trusted, then the dialog should not come up at all, but I want to confirm that this is the right track.

**Comment by mickaelistria** [comment]
> I think this meets the requirements/goal of this issue, right?

yes, that seems perfect!

**Comment by mickaelistria** [comment]
Thanks @merks . Is #131 enough to close this issue or is there some work left?

**Comment by merks** [comment]
I suppose a test would be very nice, but that seems like a lot of work and I don't have the time for that.   I have manually tested different combinations such as trusting the certificate or trusting the PGP key and ensuring that there is no prompt in either of those two cases.  So unless you or someone wants to invest time in a test case, we could close it...
