### ISSUE TITLE
Option to disable PGPSignatureVerifier?

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#16]
We have a discussion here where a site contains an invalid key: 
https://github.com/eclipse/tycho/discussions/803

Is there any mean to disable PGP signature validation or would it be suitable to add such an option to P2?

**Comment by mickaelistria** [comment]
p2 does lookup `EngineActivator.getContext().getProperty(EngineActivator.PROP_UNSIGNED_POLICY);` to decide whether to skip signature checks.

**Comment by laeubi** [comment]
@mickaelistria I don't think that this option applies here and running the example with `-Declipse.p2.unsignedPolicy=allow` still fails the build, as it is not *unsigned* but the signature is there but *invalid*, I'm not sure if we should support this at all but probably there are pro and cons to be considered...

**Comment by merks** [comment]
Indeed, that option only allows content with untrusted certificates or untrusted keys to be installed without prompting.   Also, given that the p2 director as used by Tycho auto-approves all certificates and all keys, that makes no difference either.

But somehow I'm doubtful about this request.  Do we really want to allow content where the signature is **invalid** or perhaps where the checksums indicate the artifact is invalid?  This gets to be a supply chain hacking loophole that I'm not sure we ought to open with an option in the framework.  If a signature is invalid, it would seem best to investigate what is going wrong...

**Comment by laeubi** [comment]
> But somehow I'm doubtful about this request. Do we really want to allow content where the signature is **invalid** or perhaps where the checksums indicate the artifact is invalid?

That's why I opened the ticket and unless #4  is not fixed issues seems the best place to discuss such things :-)
