### ISSUE TITLE
Switch to Java11 HttpClient

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#205]
ECF now includes the Java 11 HttpClient (see https://github.com/eclipse/ecf/pull/12#issuecomment-1322998036)

We should include this as early as possible to have enough time to test and get feedback and/or regressions.

I could see two possible options:

1. we **only** include Java 11, if there is any issue users can de-install it and install Apache Client5 instead, but it might be problematic if it totally fails
2. we **additionally** include Java 11, if there are issues users can de-install it and should be back at Apache Client5, but there is some risk that the presence of Apache Client5 hides some issues we won't see

FYI @akurtakov what do you think? Maybe (2) for 2023-03 and switch to (1) in 2023-06?

**Comment by akurtakov** [comment]
I'm off till end of year starting today. In previous cases (e.g. httpclient 3->4, 4->5) Platform went with just including latest and it being default. If there is issue by the time of M2, revert to httpclient 5 can be done.

**Comment by vogella** [comment]
Cool

**Comment by vogella** [comment]
If possible switch to the new provider early M1 to find issues with it. IMHO it would be a nice win to get rid of the httpclient dependency.

**Comment by laeubi** [comment]
It should now be available in the target platform, so if you like, just exchange the features and open a PR so we can see what happens :-)

**Comment by vogella** [comment]
> It should now be available in the target platform, so if you like, just exchange the features and open a PR so we can see what happens :-)

I leave that to the more involved people like you or Alex. Would be strange to me to change a feature without having worked / looked at the actual change.

**Comment by laeubi** [comment]
I created
- https://github.com/eclipse-equinox/p2/pull/206

**Comment by laeubi** [comment]
I think I have prepared all that is required for "platform" here, Tycho already uses a custom transport for this so if someone is interested in bring this forward it would be good to take over.

**Comment by akurtakov** [comment]
I hope to try it out soon(ish). But others are more than welcome to try themself and report issues.

**Comment by vogella** [comment]
I see that Tycho 4 will start using this. Why not merge this one and revert if we see issue with it?

**Comment by laeubi** [comment]
Tycho 4 is using an own transport independent from P2... last time I checked P2 test failed, so someone is needed to look into this:
- https://github.com/eclipse-equinox/p2/pull/206

**Comment by akurtakov** [comment]
Now that this is in an I-build , will java11 httpclient be used instead of apache hc one if both providers are installed ?

**Comment by akurtakov** [comment]
Actually the httpclient5.source ones would better be gone one we are sure of the implementation.

**Comment by merks** [comment]
There seem to be many references to the older things:

![image](https://github.com/eclipse-equinox/p2/assets/208716/f361d32d-25b5-483f-b058-8abb2cd7ea2f)

**Comment by merks** [comment]
I would try to help more, but I really need to get a new version of ant (1.10.14) ready ASAP...

**Comment by akurtakov** [comment]
I've done installation and it works fine but having people behind weird proxies test would be much appreciated.

**Comment by merks** [comment]
Yes, I tested the installer and stuff too a few months ago.  It all seems fine.  But weird networks with firewalls and proxies with authentication are my biggest concern...  

Perhaps @sratz is familiar with such environments and has time to try it out...

**Comment by mickaelistria** [comment]
> I've just updated my SDK to latest I-Build and I see that the httpclient5 ECF connector was removed as part of the update.

It's actually not an issue for me, but more the confirmation that the installation and replacement process is going fine. We do not want httpclient5 anymore, but httpclientjava (which is provided with the update).
I would suggest to close this issue; and open new ones to get rid of remaining references to httpclient5.

**Comment by sratz** [comment]
I know that httpclient5-based ECF comes with a special `org.eclipse.ecf.provider.filetransfer.httpclient5.win32` bundle specifically for NTLM and SPNEGO proxy authentication. I have no idea how well these environments are supported by the Java 11 HTTP client (I also don't have access to such environments to test it).

EGit offers a choice to switch between the HTTP client implementations:
![image](https://github.com/eclipse-equinox/p2/assets/14908423/16353cf5-780b-42e9-bfba-7a2ce3ec8c3a)

Could be an alternative to allow for a phased transition and to have a fallback?

**Comment by merks** [comment]
Even if such a thing is feasible, no one will actually invest effort to implement that.  😱

**Comment by laeubi** [comment]
Maintaining **two** implementations is actually the opposite of what the goal here is.
Nerveless every user with special demands *can* uninstall the java11 http feature and install any alternative implementation, its just a matter of adding the ECF update site (maybe @merks might be gracious to help enhancing the `p2.inf` of these features that installing *one* implementation automatically remove *the others*) I think that's fair enough.

**Comment by merks** [comment]
The following might not determine the winner, but it does ensure that `org.eclipse.ecf.filetransfer.httpclientjava.feature` is a contender for the title:

https://github.com/eclipse-equinox/p2/blob/1af3d0fcb08073e7c9fe07a914988d3e7b2da816/features/org.eclipse.equinox.p2.core.feature/feature.xml#L26

FYI, I've been able to get the installer fully working with the new implementation, including in Oomph's ECFURIHandlerImpl.

I think we could no proceed with the remaining cleanup...

**Comment by merks** [comment]
I believe the cleanup is done.  

A new problem with authentication is tracked by this new issue:

https://github.com/eclipse-equinox/p2/issues/330
