### ISSUE TITLE
Use https:// not http:// for prompt for add repository

### ISSUE THREAD

**Issue by ajohnson1** [eclipse-equinox/p2#209]
See https://github.com/eclipse-equinox/p2/blob/23e53212405d35827302deb2913616b2a3e637eb/bundles/org.eclipse.equinox.p2.ui/src/org/eclipse/equinox/internal/p2/ui/dialogs/RepositoryNameAndLocationDialog.java#L180

If this was 'https://' then it would encourage users to specify a secure site.

**Comment by merks** [comment]
A PR would be very welcome!

  It's really easy to set up an IDE:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md
https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup&show=true

Or a smaller one for just Equinox things:

https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-equinox/equinox/master/releng/org.eclipse.equinox.releng/EquinoxConfiguration.setup&show=true
