### ISSUE TITLE
Remove deprecated pack200 support

### ISSUE THREAD

**Issue by akurtakov** [eclipse-equinox/p2#238]
It has been deprecated 2 years ago in https://bugs.eclipse.org/bugs/show_bug.cgi?id=572043, deprecation period ended and now that Java 17 is required there is not even theoretical chance for this to be useful anymore.

**Comment by akurtakov** [comment]
Removal documentation updated via https://github.com/eclipse-platform/eclipse.platform.common/pull/130

**Comment by iloveeclipse** [comment]
@akurtakov : there are PDE test fails in https://download.eclipse.org/eclipse/downloads/drops4/I20230330-1800/testResults.php related to this removal.

Do you plan / can work on them? 

See https://download.eclipse.org/eclipse/downloads/drops4/I20230330-1800/testresults/html/org.eclipse.pde.build.tests_ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

**Comment by akurtakov** [comment]
Let me look into them.
