### ISSUE TITLE
Automatic update scheduler does not notify user about updates that target write-protected  components

### ISSUE THREAD

**Issue by basilevs** [eclipse-equinox/p2#254]
The Eclipse update check is not showing any notification of available updates when the user does not have sufficient access privileges. This issue occurs even when automatic updates are enabled in the preferences. 

### Test steps

- Install an [old Eclipse Package](https://www.eclipse.org/downloads/packages/release/2022-12/r)
- Disable write access to the installation directory 
  - or switch to user account with limited privileges, that lacks such access
- Start Eclipse
- Configure Preferences/Install/Update/Available Software Site to add [the latest Eclipse update site](https://download.eclipse.org/releases/2023-03)
- Invoke Help/Check for Updates
- Wait for pending jobs to complete
- Verify that some update are present, but none are available due to "Insufficient access privileges to apply this update."
- Cancel the update dialog.
- Configure Preferences/Install/Update/Automatic Updates/Update schedule/Look for updates each time Eclipse IDE is started
- Apply and restart
### Expected Result
The user should receive some kind of notification indicating that the system administrator may be able to install updates.
### Actual Result
The update check is completely silent, no indication of available update is given.
### Entrypoint
The entrypoint is org.eclipse.equinox.internal.p2.ui.sdk.scheduler.AutomaticUpdater.validateIusToUpdate() - it ignores all non-installable updates.
### Suggested Fix
Warn user about all updates. Enable new behavior by Preferences. 
This will allow security-sensitive products to  inform the user about updates, without annoying users in  non-secure contexts.

**Comment by merks** [comment]
Are you able to install new software into this read-only installation?  That does normally work...

**Comment by basilevs** [comment]
@merks yes, new software can be installed. While some components receive updates, others are silently left obsolete and unsafe.

**Comment by merks** [comment]
And a manual check-for-updates does find updates, right? (It does for me.)  So it's just the automatic thing that doesn't work at all.  It seems reasonable to expect that this should work.  After all, the user could update their "surrogate configuration"...

**Comment by basilevs** [comment]
Manual check for updates works (per original description). We do not need the full working update - just a warning to user that some software in use is obsolete.

**Comment by merks** [comment]
Yes, that's what I thought.  Have you debugged this that you know where things are not quite right?  It would appear at a glance that maybe org.eclipse.equinox.internal.p2.ui.sdk.scheduler.AutomaticUpdater.validToUpdate(IProfile, IInstallableUnit) that's returning false so that the list of ius to update is empty...

**Comment by basilevs** [comment]
@merks  `validToUpdate()` is correct in a sense, that IU given cannot be updated. `validateIusToUpdate()` drops/ignores such updates instead of warning about them - that's why it is an "entrypoint" in the original description. Basically, if we need to fix anything, that method will be a mandatory part of such fix.

**Comment by merks** [comment]
I think the problem stems from this definition:

https://github.com/eclipse-equinox/p2/blob/2f11750cb8b4beeef3be6a03dd807466771b8102/bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/SurrogateProfileHandler.java#L45

Which is used here and basically locks the IU to prevents uninstall and updates:

https://github.com/eclipse-equinox/p2/blob/2f11750cb8b4beeef3be6a03dd807466771b8102/bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/SurrogateProfileHandler.java#L57-L73

This is clearly all intentional and the check is used in a bunch of places:

![image](https://user-images.githubusercontent.com/208716/232829135-5a5e4a28-4c42-4a70-88d5-e2bb83e8b378.png)

I'm not really sure the design intent of all those places given one might use such a property on a real (non-surrogate) profile to prevent those operations.  😞

**Comment by laeubi** [comment]
> I'm not really sure the design intent of all those places given one might use such a property on a real (non-surrogate) profile to prevent those operations. disappointed

If you define a product, you can mark features as "root", only those marked as root features can later be updated (and probably uninstalled).

**Comment by merks** [comment]
It's `IProfile.LOCK_UPDATE` specifically that concerns me not whether something is a root or not because the surrogate profile is setting that property without regard for how it is set in the underlying profile whereas the org.eclipse.equinox.p2.engine.IProfile.PROP_PROFILE_ROOT_IU property will simply reflect the value in the underlying profile...

**Comment by merks** [comment]
I think part of the design intent is properly to disable these actions in the about dialog:

![image](https://user-images.githubusercontent.com/208716/232833525-033ca610-fa09-457a-af25-1c8671e2d40a.png)

**Comment by basilevs** [comment]
@laeubi those buttons are disabled for non-root features, so your initial statement does not contradict any findings here.
Shared install just disables update for all features, not only for non-root ones. My bet would be that the design intent was to avoid complex profile merge procedure by forbidding conflicting versions of same IUs. A bonus to this solution is that a multiuser host does not have duplicates of same IUs in different pools for every surrogate profile.
I expect, that there is no quick way to make updates of shared installation work. So this bug is strictly about notification/reporting, not actual update.

**Comment by merks** [comment]
@basilevs 

Note that updates and installs are placed in the surrogate profile folder in the <home>/.eclipse folder, e.g., 
```
C:\Users\merks\.eclipse\org.eclipse.platform_4.26.0_875998641_win32_win32_x86_64
```
If we allow such check for updates to perform the check as normal, it will also happily perform the update as normal, targeting the above surrogate folder.  I get a feeling that you don't want it to actually do the update but just want a notification that an update is possible.  That's more complicated to implement, especially given that you can install additional things and check for updates does work for those additional things already...

Via a system property, I could change behavior simply not to lock all the root features, which would be easy to implement, but probably that doesn't properly address only the notification problem if that's only what you want...

**Comment by vgcpge** [comment]
I'm sorry, I thought, that updating write protected components was hard due to Profile merge issues. I'm fine with the easiest possible solution. I have a rough prototype for the warning ready, and  it is trivial, but if updates are possible, the warning is not needed!

**Comment by vgcpge** [comment]
I'm struggling finding any artifacts for the CI build that includes the changes. Should I build the P2 update site locally?

**Comment by merks** [comment]
I think it should be in the latest I-build:

https://download.eclipse.org/eclipse/updates/4.28-I-builds/

**Comment by basilevs** [comment]
Even with #256  applied and a system property defined, the behavior  exactly matches the original description.

### Test steps
Update Eclipse to https://download.eclipse.org/eclipse/updates/4.28-I-builds/I20230420-1800/
Check that installed org.eclipse.equinox.p2.engine has version 2.8.0.v20230420-0800	
Add update site https://download.eclipse.org/eclipse/updates/4.28-I-builds/I20230421-1800/
Exit Eclipse
Make its installation write-protected with `chown -R nobody:nobody`
Start a new with `open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock=true`

### Actual result
Notifications are not shown, updates are not installed
Manual check for updates produces diagnostic from original description.

What was supposed to change? Could we reopen the issue?

**Comment by merks** [comment]
Note the description:

> Use the system property org.eclipse.equinox.p2.type.lock as a mask for setting that IU property lock state, e.g., setting it to 0 will leave the mask as specified in the user profile, 1 will lock it only for uninstall, and 3 is what it does by default, which is to look for uninstall and update.

So it's used as a mask:

https://github.com/eclipse-equinox/p2/blob/30df3b9e832612881a2e058b96a3c31d5e94d70d/bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/SurrogateProfileHandler.java#L65-L76

So you want to specify either 0 or 1 depending on whether you want to allow uninstall or not...

**Comment by basilevs** [comment]
Sorry about typo. I've tried every value to no avail:

```
% open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock
% open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock
% open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock=true
% open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock=true
% open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock=0   
% open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock=1
% open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock=2
% open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock=3
% open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock=3
% open /private/tmp/eclipse/ide-2023-03/Eclipse.app --args -vmargs -Dorg.eclipse.equinox.p2.type.lock=1
```

**Comment by merks** [comment]
I’m not sure at what point the surrogate profile is created but probably once it’s created once the first time the system property has no effect.  Look in the .eclipse folder of your home folder and remove the surrogate folder.  For the real shared install the system property should be in the product ini.

**Comment by basilevs** [comment]
Partial success!

### Test Steps
Install a new Eclipse instance (in a new, unique directory) using Oomph
Change eclipse.ini to include -Dorg.eclipse.equinox.p2.type.lock=0
Update to https://download.eclipse.org/eclipse/updates/4.28-I-builds/I20230420-1800/
Add https://download.eclipse.org/eclipse/updates/4.28-I-builds/I20230421-1800/
Exit
Make write-protected
Start again
Update do not start automatically
Do explicit check

### Actual Result
Automatic updates do no happen,
But explicit check produces eliglble (non-grayed-out) options
Unfortunately, update fails with
```
eclipse.buildId=4.28.0.I20230420-1800
java.version=17.0.4.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_GE
Framework arguments:  -keyring /Users/vasiligulevich/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -keyring /Users/vasiligulevich/.eclipse_keyring

org.eclipse.equinox.p2.touchpoint.natives
Error
Sat Apr 22 13:07:08 GET 2023
Backup of file /private/tmp/eclipse/ide-2023-032/Eclipse.app/Contents/Eclipse/.eclipseproduct failed.

java.nio.file.AccessDeniedException: /private/tmp/eclipse/ide-2023-032/Eclipse.app/Contents/Eclipse/.eclipseproduct -> /var/folders/k0/n6p7cm714pj6xpsd_ngcdht80000gn/T/_private_tmp_eclipse_ide-2023-032_Eclipse.app_Contents_Eclipse_e4eeacab-439f-47a6-b7d0-e88ab6207120/_/private/tmp/eclipse/ide-2023-032/Eclipse.app/Contents/Eclipse/.eclipseproduct
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:477)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266)
	at java.base/java.nio.file.Files.move(Files.java:1432)
	at org.eclipse.equinox.internal.p2.touchpoint.natives.SimpleBackupStore.move(SimpleBackupStore.java:852)
	at org.eclipse.equinox.internal.p2.touchpoint.natives.SimpleBackupStore.moveToBackup(SimpleBackupStore.java:594)
	at org.eclipse.equinox.internal.p2.touchpoint.natives.SimpleBackupStore.backup(SimpleBackupStore.java:244)
	at org.eclipse.equinox.internal.p2.touchpoint.natives.LazyBackupStore.backup(LazyBackupStore.java:38)
	at org.eclipse.equinox.internal.p2.touchpoint.natives.actions.CleanupzipAction.cleanupzip(CleanupzipAction.java:90)
	at org.eclipse.equinox.internal.p2.touchpoint.natives.actions.CleanupzipAction.execute(CleanupzipAction.java:34)
	at org.eclipse.equinox.internal.p2.engine.ParameterizedProvisioningAction.execute(ParameterizedProvisioningAction.java:42)
	at org.eclipse.equinox.internal.p2.engine.Phase.mainPerform(Phase.java:186)
	at org.eclipse.equinox.internal.p2.engine.Phase.perform(Phase.java:99)
	at org.eclipse.equinox.internal.p2.engine.PhaseSet.perform(PhaseSet.java:50)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:95)
	at org.eclipse.equinox.internal.p2.engine.Engine.perform(Engine.java:49)
	at org.eclipse.equinox.p2.operations.ProvisioningSession.performProvisioningPlan(ProvisioningSession.java:181)
	at org.eclipse.equinox.p2.operations.ProfileModificationJob.runModal(ProfileModificationJob.java:76)
	at org.eclipse.equinox.p2.operations.ProvisioningJob.run(ProvisioningJob.java:188)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I will retry same test, as I see not reason for either  absence of notification or this error.

**Comment by merks** [comment]
Note that the installer by default installs using a shared bundle pool so making only the installation folder read only does not work.  Use the menu to look at the ask a question details. 

It’s probably easier to download a 4.28 integration build

https://download.eclipse.org/eclipse/downloads/

**Comment by basilevs** [comment]
Thanks for the advice and sorry for the confusion.
I've downloaded https://download.eclipse.org/eclipse/downloads/drops4/I20230420-1800/download.php?dropFile=eclipse-platform-I20230420-1800-macosx-cocoa-aarch64.dmg
and automatic update notifications are now shown. The fix seem to be working. Thanks!
The update still fails with:
```
An error occurred while uninstalling
session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Uninstall, operand=[R]org.eclipse.platform_root 4.28.0.v20230420-1800 --> null, action=org.eclipse.equinox.internal.p2.touchpoint.natives.actions.CleanupzipAction).
Backup of file /private/tmp/eclipse/Eclipse.app/Contents/Eclipse/.eclipseproduct failed.
/private/tmp/eclipse/Eclipse.app/Contents/Eclipse/.eclipseproduct -> /var/folders/k0/n6p7cm714pj6xpsd_ngcdht80000gn/T/SDKProfile_6b5deade-0b18-4032-9623-9fb32eaf0ff4/_/private/tmp/eclipse/Eclipse.app/Contents/Eclipse/.eclipseproduct
```
Should I create a bug against Eclipse Platform?

**Comment by merks** [comment]
I’m answering from a car so I cannot test on Windows right now.  The /private/tmp makes me wonder where you have installed. Maybe some mac gatekeeper thing is involved?

**Comment by basilevs** [comment]
That's some scary dedication! Please take care not to get into an accident over unpaid labor XD. 

I had to remove quarantine flag for Eclipse to start at all, but that is a standard procedure for unnotarized binaries: `xattr -r -d com.apple.quarantine /private/tmp/eclipse/Eclipse.app`.

Update works, if installation directory is writable, so antivirus tooling is unlikely to be the culprit.

To eliminate "strange location" factor, I've installed a fresh copy in `/Applications` and got similar result:
```
An error occurred while uninstalling
session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Uninstall, operand=[R]org.eclipse.platform_root 4.28.0.v20230420-1800 --> null, action=org.eclipse.equinox.internal.p2.touchpoint.natives.actions.CleanupzipAction).
Backup of file /Applications/Eclipse4.app/Contents/Eclipse/.eclipseproduct failed.
/Applications/Eclipse4.app/Contents/Eclipse/.eclipseproduct -> /var/folders/k0/n6p7cm714pj6xpsd_ngcdht80000gn/T/SDKProfile_961fcce2-a823-4107-a22a-c71cb3138ccc/_/Applications/Eclipse4.app/Contents/Eclipse/.eclipseproduct
```

**Comment by merks** [comment]
I got this failure on Windows:

> org.eclipse.equinox.internal.p2.touchpoint.natives.actions.UnzipAction error unzipping zipfile: C:\Users\merks\.eclipse\org.eclipse.platform_4.28.0_1429678108_win32_win32_x86_64\p2\org.eclipse.equinox.p2.core\cache\binary\org.eclipse.sdk.ide.executable.win32.win32.x86_64_4.28.0.I20230421-1800destination: D:\Users\test17\read-only\eclipse

But I think the executable itself can't really just be only physically located in the surrogate...

I'll need to investigate further if this same type of problem arises when installing into an installation that hasn't turned off the locking.  But I'm traveling and really don't have much time until Monday...

**Comment by merks** [comment]
For a read-only installation without these things enabled by the new system property, one is prevented from installing such a feature.   It refuses to turn an install attempt into an update explaining that the feature is locked for updates.  So maybe this approach is a failed experiment. I should note though that despite the logged error, mostly the update seems to have worked. In the end, any touchpoint operation that must operate on the real read-only location is going to fail in this way and that's probably why the original designers disabled all updates to all pre-installed things, even though some can work fine.

I don't personally have the time to work on something fancier...

**Comment by vgcpge** [comment]
Could you please reopen the issue then? I promise to come up with a PR to notify the user of the original problem.

**Comment by basilevs** [comment]
Pull request #258 is ready for review.
It was a major pain to test via feature patches. I wonder how is it normally done...
