### ISSUE TITLE
Could not instantiate step:org.eclipse.equinox.p2.processing.Pack200Unpacker

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#308]
```
[ERROR] All attempts to read artifact osgi.bundle,org.apache.batik.i18n,1.14.0.v20210324-0332 failed:
[ERROR]    An error occurred while transferring artifact canonical: osgi.bundle,org.apache.batik.i18n,1.14.0.v20210324-0332 from repository https://download.eclipse.org/releases/2021-09/202109151000:
[ERROR]       Retry another mirror:
[ERROR]          download from https://mirror.ibcp.fr/pub/eclipse/releases/2021-09/202109151000/plugins/org.apache.batik.i18n_1.14.0.v20210324-0332.jar failed
[ERROR]    An error occurred while transferring artifact packed: osgi.bundle,org.apache.batik.i18n,1.14.0.v20210324-0332 from repository https://download.eclipse.org/releases/2021-09/202109151000:
[ERROR]       Result of processing steps.:
[ERROR]          Could not instantiate step:org.eclipse.equinox.p2.processing.Pack200Unpacker
```

Now e removed pack200 support it seems there are some problems if it is tried to transfer artifacts from some mirrors, we should somehow add special handling that such requests are just a noop / redirected to the plain artifact. I'm not even sure if the packed artifact is actually used or if it is just a problem of reading that metadata.

**Comment by merks** [comment]
The error messages suggest that **all** attempts have failed, including 'artifact canonical`.  We've disabled this support years ago.  Can it really be the case that only just now we a problem?  I suspect there was a network/host problem when this occurred and that the problem can't be reproduced...

**Comment by laeubi** [comment]
Yes it seems to be a bad choice of a mirror here, **but** what makes me a bit curious is the `Could not instantiate step:org.eclipse.equinox.p2.processing.Pack200Unpacker` so as there is no more Pack200 support I would expect we actually never try to use it anyways...

**Comment by merks** [comment]
I agree it should no longer try to use something that will definitely not work and is known not to work.   

I seem to recall I had problems with mirroring as well where it should also skip trying to mirror the packed things rather than fail.

**Comment by akurtakov** [comment]
This was one hell of a removal in so many places and it looks like I missed some.

**Comment by akurtakov** [comment]
I can't find Pack200Unpacker anywhere in the aggregator so I'm quite puzzled who/where defines this step. Is this error seen in the IDE or on the console/Tycho?

**Comment by akurtakov** [comment]
Ah, it makes sense now except for the fact that this mirror seems to add (?) this step or otherwise all other mirrors should have failed the same way.

**Comment by laeubi** [comment]
I think that the "canonical" has failed (maybe a short network outage), then P2 tries the next descriptor (packed) and failed because it can't load the step afterwards.

I could think about filtering any descriptors that use the `org.eclipse.equinox.p2.processing.Pack200Unpacker` or make a better error message (e.g. implements `org.eclipse.equinox.p2.processing.Pack200Unpacker` that throws a meaningful message), even though this might still make the mirror request fail but the current message looks like a P2 bug rather than a network failure.

**Comment by akurtakov** [comment]
Actually making p2 to filter/ignore format=packed artifacts might be better solution.

**Comment by merks** [comment]
I think this might be a good test case to look at:

**Comment by akurtakov** [comment]
I'll look into this one but I doubt I can make it by tomorrow for RC1.

**Comment by laeubi** [comment]
@akurtakov don't worry, but would be great to look into, I was now able to capture this here:

https://github.com/eclipse-tycho/tycho/runs/16125467596

**Comment by laeubi** [comment]
Also here such failure is indicated while running the tests (macos this time):

https://github.com/eclipse-tycho/tycho/actions/runs/5945218436/job/16123908598?pr=2723

I'll leave the PR as is for now (a rerun will probably solve them) if one likes to take a look at the logs, just let me know if I can restart the builds.

**Comment by akurtakov** [comment]
I have a draft doing exactly that already.

**Comment by merks** [comment]
@akurtakov 

You mean a PR for Tycho or a PR for p2?  I was going to have a quick look at this p2 issue, but I don't want to do duplicate work...

**Comment by akurtakov** [comment]
For p2. I will publish when I get home

**Comment by merks** [comment]
Very good!

**Comment by laeubi** [comment]
By the way if we have a solution that seems quite local and it could be included in RC1 that would be welcome (as Tycho is usually off by one in the release) but as @merks mentioned it would also be okay for the next release.

**Comment by merks** [comment]
I agree a safe fix would be nice.  The fact that mirroring is kind of broken has already bitten me in the past, but that's my fault because I should have opened an issue like @laeubi did...

**Comment by akurtakov** [comment]
@merks MirrorRequestTest is totally bogus as the returned statuses are actually set by the test itself and this has been the case for a decade.

**Comment by merks** [comment]
I see!   I only looked there because I saw these repos contains such content:

![image](https://github.com/eclipse-equinox/p2/assets/208716/238fb34d-2bce-457d-9ebf-28a14073e2ea)
