### ISSUE TITLE
Latest 4.30 I builds for our product - Missing contraints org.w3c.css.sac and others

### ISSUE THREAD

**Issue by Phillipus** [eclipse-equinox/p2#327]
I'm testing our Archi RCP product against the latest 4.30 I builds and it no longer launches with the following errors:

![Image 001](https://github.com/eclipse-equinox/p2/assets/600504/6b3520b7-4618-4ea7-ac25-f66c517aa4cf)

This is our product file - https://github.com/archimatetool/archi/blob/master/com.archimatetool.editor.product/archi.product

I notice this recent change https://github.com/eclipse-equinox/p2/commit/f891c9f8b95f6f3faee4eda8fcce84460e32232b from @merks - is there anything I need to change at my end because I can't see what I can do?

**Comment by laeubi** [comment]
Just to be sure, if you just use "Continue" does it work?

**Comment by Phillipus** [comment]
> Just to be sure, if you just use "Continue" does it work?

No, I'm getting lots of `Unresolved requirement: Import-Package: org.w3c.css.sac` and so on errors. 

I'm using this target:

```
<target name="Archi">
<locations>
    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/eclipse/updates/4.30-I-builds"/>
        <unit id="org.eclipse.sdk.feature.group" version="0.0.0"/>
    </location>
    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/releases/2023-09"/>
        <unit id="org.eclipse.emf.compare.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.jgit.feature.group" version="0.0.0"/>
        <unit id="org.eclipse.jgit.ssh.apache.feature.group" version="0.0.0"/>
    </location>
    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/tools/orbit/downloads/2023-06"/>
        <unit id="org.slf4j.binding.simple" version="1.7.30.v20221112-0806"/>
        <unit id="org.mockito.mockito-core" version="4.8.1.v20221103-2317"/>
    </location>
</locations>
</target>
```

And, in Eclipse 4.28, launching the product from the product file "Launch an Eclipse application in debug mode".

**Comment by merks** [comment]
This bundle provides/exports the required packages:

![image](https://github.com/eclipse-equinox/p2/assets/208716/7b21f1bf-21d0-4052-938c-cb9f49ff6e21)

![image](https://github.com/eclipse-equinox/p2/assets/208716/2aeae5e0-8156-445e-bbfc-cb4564722faf)

**Comment by Phillipus** [comment]
> This bundle provides/exports the required packages:

I'm sorry, I don't understand. Those eclipse plug-ins such as `org.eclipse.e4.ui.css,core` have these dependencies, surely they should be resolved automatically? They did up until recently.

**Comment by merks** [comment]
You mention testing your product, but how exactly are you testing it?   If I resolve your target platform

![image](https://github.com/eclipse-equinox/p2/assets/208716/8d5cd349-b705-43c6-aa32-740689809f18)

the expected/required things are there:

![image](https://github.com/eclipse-equinox/p2/assets/208716/86ec2eac-3a8b-4449-b6d0-266f102abb49)

But I don't know anything about your launch configuration.  Is it missing something?

**Comment by Phillipus** [comment]
Yes, I see the `org.eclipse.orbit.xml.*` plug-ins too. But when I open the plug-in dependencies tab for `org.eclipse.e4.ui.css.core` I see red crosses:

![Image 002](https://github.com/eclipse-equinox/p2/assets/600504/2a6de9e1-7256-4b94-9a9e-8886099b3f35)

**Comment by Phillipus** [comment]
And here:

![Image 003](https://github.com/eclipse-equinox/p2/assets/600504/62447247-315a-4d4d-9cfa-9b6511edc87f)

**Comment by Phillipus** [comment]
> You mention testing your product, but how exactly are you testing it?

In Eclipse 4.28, I launch the product from the product file's "Launch an Eclipse application in debug mode" link.

**Comment by merks** [comment]
I'm not sure what to say.  I keep Oomph development environment's target platform up-to-date in a Committers 2023-09 installation and it all looks fine:

![image](https://github.com/eclipse-equinox/p2/assets/208716/6feef928-a13c-4553-b4d9-2d0a2713aef7)

Maybe a PDE bug in an older installation?  There's certainly no p2 bug here...

**Comment by Phillipus** [comment]
I'm using Eclipse 4.28 with the target set to 4.30 I builds. I'm now testing using Eclipse 4.29 and I'm no longer see the errors and the RCP but theming is disabled in the launched RCP app.

**Comment by merks** [comment]
That's a little strange.   I can't think of a good reason why such a thing would be broken in a 4.28 IDE.  Resolving package imports to the bundles that export them is a pretty basic and widely used functionality.

**Comment by Phillipus** [comment]
So I can get it launched now using Eclipse 4.29 and ensuring "Use features from workspace if available" is checked in the launch configuration.

But I don't understand why the dependencies are not resolved using a 4.28 IDE.

Sorry that I reported this in the wrong place, it's hard to determine if the issue is caused by P2 or PDE.

**Comment by merks** [comment]
No problem.  There's something definitely strange about what you saw in that older IDE.  PDE uses a bundle resolver to do this wiring, which is different than what p2 does to resolve dependencies when building a target platform itself, and is also differently implemented than what OSGi actually does at runtime to wire real runtime bundles.  As a user, who's to know such technical details?  

I'm just glad we were able to help you resolve the issue relatively quickly.

**Comment by Phillipus** [comment]
> I'm just glad we were able to help you resolve the issue relatively quickly.

And I appreciate that help, thank-you. :-)

**Comment by HannesWell** [comment]
This is probably yet another reincarnation of https://github.com/eclipse-pde/eclipse.pde/issues/429 combined with the fact that not resolved bundles are not added to a launch automatically.
Looking at the MANIFEST.MF of `org.eclipse.orbit.xml-apis-ext` I see the package imports
```
Import-Package: org.w3c.dom,org.w3c.dom.events
```
Both packages are provided by (recent) JVMs, but before 4.29 PDE didn't consider the JVM as provider of those packages and therefore `org.eclipse.orbit.xml-apis-ext` probably didn't resolve and was therefore not added to the runtime as requirement. If you would have added it explicitly in 4.28 the validation error probably would have poped up for `org.eclipse.orbit.xml-apis-ext` saying that the two imported packages could not have been resolved, but at runtime the resolution would have succeeded.
If you still have the 4.28 Eclipse you can check the `Target Platform State` view and set `Show only unresolved plug-ins` in the menu and see if `org.eclipse.orbit.xml-apis-ext` is marked as unresolved.

**Comment by Phillipus** [comment]
> If you still have the 4.28 Eclipse you can check the Target Platform State view and set Show only unresolved plug-ins in the menu and see if org.eclipse.orbit.xml-apis-ext is marked as unresolved.

Indeed, that is the case:

![r](https://github.com/eclipse-equinox/p2/assets/600504/c28a33b0-27ed-4b44-939f-b3b177d286df)

**Comment by merks** [comment]
It's great to see an explanation for the problem!  It is also interesting to note,  in light of the following discussion, that the package import, even without a version constraint, causes problem:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1349#issuecomment-1722834624

In terms of being in "recent" JVMs, looking at the OSGi profiles, I think it's fair to say that these packages were present even in ancient JVMs that are far past end-of-life:

![image](https://github.com/eclipse-equinox/p2/assets/208716/f68fafc1-7995-495f-967f-efd1b6db06ed)

**Comment by laeubi** [comment]
> In terms of being in "recent" JVMs, looking at the OSGi profiles, I think it's fair to say that these packages were present even in ancient JVMs that are far past end-of-life:

It is the other way round, the package was provided by the JVM earlier, but now is now in the (JPMS) [module java.xml](https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/module-summary.html), that means:

1. it could be missing from a stripped down JVM
2. there is never any guarantee that the package is of the desired version

So "the package import, even without a version constraint, causes problem" is only a very specific PDE issue when using it only indirectly *and* rely on the automatic adding of dependencies in PDE, so as @HannesWell explained, if one would have added it directly there wouldn't be any issue at all except

1. you are using a modern JVM that has stripped javax.xml
2. you need a specific feature in a specific version of the spec

**Comment by merks** [comment]
These are all facts, none of which contradict the fact that these are also in ancient profiles.  I think we can also all agree that none of these facts change the fact that we **should** have package import of org.w3c.dom.events, without a version constraint, so that it can resolved to a JRE, if that JRE provides it.  It's also definitely a fact that one can jlink a JRE without the java.xml module such that the package is not in that JRE.  So the facts all clear, we all "violently" agree on them. and the actions that we should take are no different from the ones that have been taken.  Unfortunately that still caused a problem, though fortunately one that Hannes so kindly fixed during the previous release cycle!!

**Comment by laeubi** [comment]
> I think we can also all agree that none of these facts change the fact that we should have package import of org.w3c.dom.events, without a version constraint

If proper `uses` constraint on exposed API is provided, sadly Eclipse Bundles often lack this important information.

**Comment by Phillipus** [comment]
> If you would have added it explicitly in 4.28 the validation error probably would have poped up for `org.eclipse.orbit.xml-apis-ext` saying that the two imported packages could not have been resolved, but at runtime the resolution would have succeeded.

Yes, that's correct. I just re-tested using 4.28 IDE and 4.30 I build target. I manually added the  `org.eclipse.orbit.xml-apis-ext` plug-in to the debug launch configuration and got this:

![debug](https://github.com/eclipse-equinox/p2/assets/600504/14abac0b-84c3-492d-ae93-9d33a9add161)

I clicked "Continue" and the RCP app ran OK.
