### ISSUE TITLE
Latest 4.30 I-build for target - Missing contraints org.eclipse.jetty.*

### ISSUE THREAD

**Issue by Phillipus** [eclipse-equinox/p2#344]
I'm testing our RCP product against the latest 4.30 I build (I20231001-1800) target and it no longer launches with the following errors:

![errors](https://github.com/eclipse-equinox/p2/assets/600504/f1b51cf9-3ced-431c-9022-255903b1a78a)

The Target Platform State view:

![errors 2](https://github.com/eclipse-equinox/p2/assets/600504/341dfced-805b-456d-bb36-85f968f5187e)

**Comment by Phillipus** [comment]
This is the simplified target file:

```xml
<target name="Archi">
<locations>
    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/eclipse/updates/4.30-I-builds"/>
        <unit id="org.eclipse.sdk.feature.group" version="0.0.0"/>
    </location>
</locations>
</target>
```

**Comment by Phillipus** [comment]
I never know whether to report issues like this against P2 or PDE, can someone advise?

**Comment by akurtakov** [comment]
I have a working help system with https://github.com/eclipse-equinox/equinox/pull/317 there are couple of issues (see failing tests) but without the new bundles in the target platform I can't test. 
Here is my question - what do you think should I put the migration now and continue working on fixes for the issues or keep current till issues are fixed (which exposes this issue instead)? 
I don't see other ways unfortunately. 
Of course if someone helps with debugging the issues and fixing faster it will happen faster. Also worth noting - you(almost everyone!) are probably as knowledgable on this part of the codebase as me.

**Comment by Phillipus** [comment]
Sorry if I misunderstand the conversation here...are you saying this is an intermediate state in the I-builds and this is a known issue? If so, apologies, I just thought it was worth reporting.

**Comment by merks** [comment]
It's always worth reporting an issue and in the end, if it's the wrong place, oops, but no hard done...

But yes, my sense is that this is an intermediate state and it's best not to spend time on this until it's fully stabilized.  But that's just my opinion and @akurtakov may have a different one...

**Comment by akurtakov** [comment]
It's an intermediate state which I try to solve ASAP. I was not aware of the issue and I don't plan looking into what/why goes wrong as it would delay moving out of this state.

**Comment by Phillipus** [comment]
> if it's the wrong place, oops, 

What is the right place for this kind of issue?

> It's an intermediate state which I try to solve ASAP. I was not aware of the issue and I don't plan looking into what/why goes wrong as it would delay moving out of this state.

Sorry, I just test the latest builds and report issues in case they're not known.

**Comment by akurtakov** [comment]
Jetty 10 is gone in latest I-build. Would you please retry with it?

**Comment by Phillipus** [comment]
I tested against I build `4.30.0.v20231004-0750`. There are still some problems:

![jetty](https://github.com/eclipse-equinox/p2/assets/600504/d7483314-f174-4a46-8902-607f5225f5bb)

**Comment by Phillipus** [comment]
Note to self to simplify testing this (rather than setting a new target in my workspace each time):

1. Download latest I build Eclipse SDK from here - https://download.eclipse.org/eclipse/downloads/
2. Launch Eclipse
3. Open the "Target Platform State"
4. Select "Show only unresolved plug-ins" option

**Comment by akurtakov** [comment]
@HannesWell IMHO this is the reason for the pde.build test failure too. As install and runtime works this should mean that equinox and p2 resolve properly but pde fails.

**Comment by mickaelistria** [comment]
I agree with @akurtakov , everything is fine in Tycho and plain p2 (otherwise the application wouldn't be provisioned at all), so it really looks like a PDE bug. I believe the way the `State` object is initialized in `BundleValidationOperation` may miss some system packages are not visible.
In any case, I would recommend closing it here and opening this issue in PDE.

**Comment by Phillipus** [comment]
> In any case, I would recommend closing it here and opening this issue in PDE.

https://github.com/eclipse-pde/eclipse.pde/issues/779

**Comment by HannesWell** [comment]
As a back-reference, it looks like Jetty declares the wrong BREE:
https://github.com/eclipse-pde/eclipse.pde/issues/779#issuecomment-1747335348
