### ISSUE TITLE
Capture information about a product IUs installMode="root" dependencies as filtered requirements

### ISSUE THREAD

**Issue by merks** [eclipse-equinox/p2#423]
It's currently the case that all information about a product's install root features are not captured in the p2 metadata by the ProductAction.  As a result, the EPP packages must manually maintain this information in the product's p2.inf:

https://github.com/eclipse-packaging/packages/blob/master/packages/org.eclipse.epp.package.committers.product/p2.inf

Recording that information in two separate places is both tedious and error-prone, e.g.,

1. https://github.com/eclipse-packaging/packages/blob/61a7d9829955ec5fcc2df975d73a542f6c700336/packages/org.eclipse.epp.package.committers.product/p2.inf#L29-L31
2. https://github.com/eclipse-packaging/packages/blob/61a7d9829955ec5fcc2df975d73a542f6c700336/packages/org.eclipse.epp.package.committers.product/epp.product#L234

I propose to capture the information as a normal requirement though with a filter that disables the requirement by default.  E.g., for a product IU with id `org.example.product`  requiring `<feature id="org.example" installMode="root"/>` the product action would synthesize a requirement with this filter:
```  
(|(org.example.product.install.mode.root=true)(org.eclipse.equinox.p2.install.mode.root=true)))
```

This can be made to work well even for a required feature that specifies a filter by simply composing the filter expression, e.g., 
```
(&(osgi.arch=x86)(osgi.os=win32)(osgi.ws=win32)(|(org.example.product.install.mode.root.install.mode.root=true)(org.eclipse.equinox.p2.install.mode.root=true)))
```

With this this approach one can ensure that a product's requirements are fully installed (or resolved) using either `org.example.product.install.mode.root=true` (selectively for one product) or `org.eclipse.equinox.p2.install.mode.root=true` (collectively for all products) in the revolver's context IU's properties.    This could be used, for example, even to improve target resolution, eliminating the need for redundantly specifying required units.  It will definitely simply EPP's releng process...

**Comment by merks** [comment]
When EPP switched many of its features to use `installMode="root"`, purely in order to allow such features to be uninstalled a few years ago, it became no longer possible to determine which features are required by a product purely from the p2 metadata.  That information is needed by the Oomph's product catalog generator (for the installers).  The solution at that time was to add back the requirements, though with filters, **exactly** like what the associated PR does automatically.  In this way, the requirement can still be uninstalled and yet the requirement details are are also still known and available.  So that's the use case why it's needed for EPP and Oomph.  The general use case is to allow a p2 direct to install a full product purely from the product's update site.

And yes, the p2 director installs each root feature separately, and because the product IU has no unfiltered requirement on such features, it's possible to uninstall any such "root" feature.  That's the use case for `installMode="root".`

I don't think Tycho has so much of a use case, except maybe as a performance enhancement that would allow it to install the product (via p2 director) in a single step rather than one additional step per root feature as it current does...

**Comment by laeubi** [comment]
@merks from your description it reads like you want the other way round:

1. have *all* features mentioned as requirements
2. have a way to filter out items that are **not** root

So one always wants to use that features as requirements but only install root items to the profile?!?

**Comment by merks** [comment]
Yes, this maps all the features to requirements, some are filtered such that they are installed/required if and only if you specify the filter.   That is the goal.  That is what what EPP is doing manually.  I desire for it to be automatic because the use case arises again with BIRT's product.  This will also be useful for the aggregator, to be able to aggregator a product and all its requirements, including install roots.  It's also useful for targlets so that one can resolve a source product IU, including all the feature roots; it's already being used that way today:

![image](https://github.com/eclipse-equinox/p2/assets/208716/ce95709d-e7c2-4470-bbac-2d8f28f59f90)

There are multiple use cases and they all work with this existing, well-supported approach of requirements with filters.

**Comment by laeubi** [comment]
> It's also useful for targlets so that one can resolve a source product IU, including all the feature roots

But why only feature roots? Non root marked features are also required for a product (ignoring plugin based products for now).

**Comment by merks** [comment]
> But why only feature roots? Non root marked features are also required for a product (ignoring plugin based products for now).

Yes, indeed non-root features are required by the product, which is why they are already handled currently:

![image](https://github.com/eclipse-equinox/p2/assets/208716/22317100-d089-4e3c-b2d9-066f45466ec1)

Only roots are completely ignored.

**Comment by laeubi** [comment]
I see, it is really a bit weird but I don't see how to change this in a backward compatible way, so your proposed solution seems fine here!

**Comment by HannesWell** [comment]
> Only roots are completely ignored.

That's indeed surprising.

**Comment by merks** [comment]
@jonahgraham 

FYI, one this is released and there is a Tycho release that uses it, we can remove the workarounds in EPP for specifying requirements on root features manually.
