### ISSUE TITLE
The use of sat4j by p2 leaks solver instances via threads spawned by sat4j

### ISSUE THREAD

**Issue by merks** [eclipse-equinox/p2#45]
I had the following horrible workaround in my marketplace  report generator:

![image](https://user-images.githubusercontent.com/208716/164242386-3953319b-7cf3-479f-9ddd-4d9dfc9481e1.png)

It would of course be much better to solve this properly in p2, especially given that the problem appears to have come back with the new sat4j version.

Here's are examples of such leaked objects:

![image](https://user-images.githubusercontent.com/208716/164243567-16618e23-1067-45b5-afbb-a51a0e295da4.png)

![image](https://user-images.githubusercontent.com/208716/164243750-03ed70f9-9129-46bd-9aef-1c4e8a48f0c9.png)

**Comment by mickaelistria** [comment]
Would it be worth making the `Projector implements AutoCloseable` so we can later use
```java
try (Projector projector = ....) {
 ...
}
```
?

**Comment by HannesWell** [comment]
> Would it be worth making the `Projector implements AutoCloseable` so we can later use

This was discussed in the linked PR: https://github.com/eclipse-equinox/p2/pull/46#discussion_r857065215

**Comment by laeubi** [comment]
Yes it was discussed there and I think we even don't need to close the projector at all but the `DependencyHelper` in this specific method call, but haven't yet found the time to look into this and since everyone seems fine I'm more focused on other "issues" ,,,
