### ISSUE TITLE
New Trust dialog opens a little too small (or shows scroll bars when it shouldn't)

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-equinox/p2#48]
I am running Xubuntu 20.04 and when I run the installer if I am prompted for Trust, the top part of the dialog is a little small so all I can see is scrollbars:

![image](https://user-images.githubusercontent.com/679236/164758507-7fc17097-9a38-4eb1-83c8-54b6d35b69cd.png)

**Comment by merks** [comment]
Here's how it comes up for me:

![image](https://user-images.githubusercontent.com/208716/164910839-095ae96d-6a6a-42f3-ae84-239322422014.png)

I used the org.eclipse.jface.layout.TableColumnLayout.TableColumnLayout(boolean) constructor with true and you can see that space is reserved for the vertical scroll as specified:
```
	/**
	 * Creates a new table column layout.
	 *
	 * @param adjustForScrollBar
	 *            <code>true</code> if the layout should reserve space for the
	 *            vertical scroll bar
	 * @since 3.12
	 */
	public TableColumnLayout(boolean adjustForScrollBar) {
		super(adjustForScrollBar);
	}
```
But apparently that doesn't always work on all platforms.

**Comment by merks** [comment]
I'll make it one character height taller in general and hope that this looks okay on Linux then too:

![image](https://user-images.githubusercontent.com/208716/164911356-224067ca-c594-44bd-b70b-a1d357d53622.png)

**Comment by merks** [comment]
The changes will be in tonight's I-Build.
