### ISSUE TITLE
"Verify provisioning operation is compatible with currently running JRE" is not working

### ISSUE THREAD

**Issue by merks** [eclipse-equinox/p2#508]
Download any 2024-03 EPP package:

https://www.eclipse.org/downloads/packages/

The option is enabled:

![image](https://github.com/eclipse-equinox/p2/assets/208716/d99d9de0-9590-4c5d-b95f-fc5622c5c66c)

Add this repo:

![image](https://github.com/eclipse-equinox/p2/assets/208716/fe0d57c7-fc78-4080-8a66-aae451442d72)

Run Help -> Check for Updates which offers these:

![image](https://github.com/eclipse-equinox/p2/assets/208716/951ef035-d24d-4721-bcf9-3d24eea975a2)

This is the result when trying to restart

![image](https://github.com/eclipse-equinox/p2/assets/208716/fcc239e2-9c4a-4106-9e23-74d93e44394a)

FYI @jonahgraham

**Comment by merks** [comment]
FYI, when I also add this site:

**Comment by jonahgraham** [comment]
Thanks Ed for this investigation work. Does "Verify provisioning operation is compatible with currently running JRE" work when the IDE is not using JustJ at all (i.e. the IDE is using Java17 from the PATH)?

**Comment by merks** [comment]
I'm 99.99% sure it does not because I have updated some of my regular development IDEs where I do in fact use a local JRE from the file system and those got broken in exactly the same way such that I had to manually edit the eclipse.ini to point at a local Java 21 JDK.

I still need to create a set of steps to reproduce the problem from a debug launch of the Eclipse SDK IDE so that this problem can be tracked down and fix.  The unfortunate thing is that we can't really fix existing 2024-03 installations so we (I) should have done this testing during the previous release cycle.  😱 

We could automatically open a page in a browser that describes the pending problem and warns people ahead of time about the pending need for Java 21...

**Comment by jonahgraham** [comment]
I look forward to your getting a reproducible case. I am hoping the issue turns out to be something that is published in the 2024-06 SimRel that fufills the Java21 requirement. We had that problem in the past where some projects had published items to SimRel that broke this.

> so we (I) should have 

definitely **we**, not just you! But I do appreciate how personally invested you are in a good user experience!

**Comment by merks** [comment]
I need to create a repo with a feature including a bundle that needs Java 21.  The SimRel repo is too complex...

I can search the repo for that capability, but it's only a a.jre.javase IUs that provide that capability:

![image](https://github.com/eclipse-equinox/p2/assets/208716/58abda6f-22f0-48ed-a5f1-bfeeff13404e)

Hopefully tomorrow I have more time.

**Comment by merks** [comment]
I created a local repository with a bundle requiring Java 21 and a feature that includes it.  When I try to install that feature, it fails like this:

![image](https://github.com/eclipse-equinox/p2/assets/208716/83285d00-07a2-4cbb-ad0c-b61cdf136228)

But that's if no repo has a.jre.javase IUs.  If I add the platform's 4.32 I-build which has a.jre.javase version 23.0 and lower, it fails differently like this:

![image](https://github.com/eclipse-equinox/p2/assets/208716/adcabe72-413d-4b20-a206-98a5c8e7fc5c)

---
If I install an older version requiring only Java 17, then add a site with a newer version that requires Java 21, and then do a Check for Updates, it finds updates, but I cannot proceed past next.  There was no feedback, until I selected the entry again and then there was this feedback presented for why I can't proceed:

![image](https://github.com/eclipse-equinox/p2/assets/208716/ca5cc91f-fcf6-48a4-95f7-65bf6ad88691)

Even when adding all these available sites (like in an EPP package):

![image](https://github.com/eclipse-equinox/p2/assets/208716/3fba9668-4612-4f0a-8647-618284fee04c)

it still fails the same way.

If I add a JustJ site that sees a JustJ Java 21 JRE:

![image](https://github.com/eclipse-equinox/p2/assets/208716/2928c63f-a0a3-49f7-9aa0-bc227e9428d5)

then I can finish the dialog:

![image](https://github.com/eclipse-equinox/p2/assets/208716/93c2be2e-f060-4166-bf69-16325707ac9a)

But note that it tells me nothing about installing JustJ 21 and in fact it doesn't install that.

---

So that leaves me still unable to explain/understand why EPP 2024-03 packages update to 2024-06 when running on a Java 17 JRE.  😢 

But then an idea struck me.

![image](https://github.com/eclipse-equinox/p2/assets/208716/47fe331b-942f-4139-9197-bcd11bb081f8)

The WWD site added by WWD's touchpoint makes the capabilities available and indeed then I can update/install things that need Java 21.  😱 

So it's not p2's that is at fault.

**Comment by jonahgraham** [comment]
Thanks Ed!
