### ISSUE TITLE
API error on org.eclipse.equinox.p2.core

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-equinox/p2#514]
Regression from https://github.com/eclipse-equinox/p2/pull/513/, API error is shown on `org.eclipse.equinox.p2.core`:

`The minor version should be incremented in version 2.11.100, since new APIs have been added since version 2.11.0`

The version should have been updated to 2.12, also "since" tags on new methods in `IProvisioningAgent` should be fixed.

**Comment by iloveeclipse** [comment]
@laeubi : we should fix it before M3. Could you please bump versions / change since tags?

**Comment by merks** [comment]
@iloveeclipse 

Hopefully this PR does the trick.
