### ISSUE TITLE
Incorrect usage of File.renameTo() in CacheManager

### ISSUE THREAD

**Issue by gloowa** [eclipse-equinox/p2#536]
Hi.

In https://github.com/eclipse-equinox/p2/blob/master/bundles/org.eclipse.equinox.p2.repository/src/org/eclipse/equinox/internal/p2/repository/CacheManager.java

in `updateCache` method there is an incorrect usage of `File.renameTo()`. It is attempted to use it to change file path to different directory, but it does not work on Windows (not sure about linux). This causes https://github.com/eclipse-m2e/m2e-core/issues/179.

I believe `java.nio.file.Files.move()` should be used instead. From `File.renameTo()` javadoc: 

> Note that the [Files] class defines the [move] method to move or rename a file in a platform independent manner

**Comment by merks** [comment]
The description here is rather vague.  As I understand it, File renameTo doesn't work on Windows to move a file to a different drive, and it doesn't work for only for just that case.  But this issue mentions no details, with the implication that File.renameTo just never works on Windows ever, which certainly can't be the case.   It's just not clear what m2e is reusing from p2 here and from the m2e issue I see no commentary from the committers about that's going on here.

**Comment by laeubi** [comment]
Independent from m2e it would not harm to use a more generic form with `java.nio.file.Files.move()`

**Comment by gloowa** [comment]
@merks You are correct, i've ran some tests, and it appears that File.renameTo is in fact able to move files between directories.

In that case, I am unable to figure out why following occurs when m2e tries to download the catalog:

```
org.eclipse.equinox.p2.core.ProvisionException: An error occurred while downloading https://github.com/eclipse-m2e/m2e-discovery-catalog/releases/download/2.x/org.eclipse.m2e.discovery.oss-catalog-2.x.jar. The cache file D:\workspace\java\.metadata\.plugins\org.eclipse.equinox.p2.discovery.compatibility\cache\downloading\discovery-1503674835 could not be renamed to D:\workspace\java\.metadata\.plugins\org.eclipse.equinox.p2.discovery.compatibility\cache\discovery-1503674835.
	at org.eclipse.equinox.internal.p2.discovery.compatibility.util.CacheManager.updateCache(CacheManager.java:228)
	at org.eclipse.equinox.internal.p2.discovery.compatibility.util.CacheManager.createCache(CacheManager.java:137)
	at org.eclipse.equinox.internal.p2.discovery.compatibility.util.TransportUtil.downloadResource(TransportUtil.java:55)
	at org.eclipse.equinox.internal.p2.discovery.compatibility.RemoteBundleDiscoveryStrategy$DownloadBundleJob.call(RemoteBundleDiscoveryStrategy.java:204)
	at org.eclipse.equinox.internal.p2.discovery.compatibility.RemoteBundleDiscoveryStrategy$DownloadBundleJob.call(RemoteBundleDiscoveryStrategy.java:1)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

This occurs when m2e tries to download the catalog (Window->Preferences->Maven->Discovery->Open Catalog). 

The paths are on the same drive and essentially it moves the downloaded file from `cache/downloading/<file>` one dir up to `cache/<file>`, and such operation works when i try to do it using `renameTo()` manually in test project, but somehow fails here.

If you google for this issue, there are more people with this problem. 

I checked and my user has full control of the directories in question, so it's not filesystem permissions (I think?). The only way this error is logged is if the  `tempFile.renameTo(cacheFile) ` returns false. I don't know how to debug eclipse itself, so i can't provide any more detail.

**Comment by iloveeclipse** [comment]
Could it be, the file is opened, so Windows doesn't allow to move it?

**Comment by gloowa** [comment]
> Could it be, the file is opened, so Windows doesn't allow to move it?

It's possible but i don't know what would have it opened... maybe replacing file move into copy and delete would help? That way at worst there would be a remnant final in the downloading directory, which i think is preferable to current behaviour...

**Comment by merks** [comment]
If the file is locked because it's open, definitely the move will fail.  Also the move can fail on Windows because a virus scanner might lock it for a short while.   But if the file is locked, it will not be possible to delete it either, though could would work. I expect Files.move would suffer problems too if the file is locked.  For this to behave properly on Windows, we'd need to figure out where the file is being opened and not closed properly (though, as I mentioned virus scanners do this too).

**Comment by gloowa** [comment]
@merks I was thinking the same thing and just checked - disabled my virus scanner (Avira) real-time protection and the issue still occurs. I've also tried to run as administrator but also to no effect...

I've monitored the file with Process Monitor and ERR_SHARING_VIOLATION occurs, so something indeed hold the file opened, but no other process than eclipse has any handles to that file:

![discovery_error](https://github.com/user-attachments/assets/ec606895-95fb-481a-98b4-63be7b5059eb)

I am not expert on this things, but one thing that catches my eye is that there is no CloseFile after 2nd CreateFile (6th line from top). Could it be that eclipse itself has the file opened and that's why move fails? Also, why is CreateFile called 3 times on the file in downloading?

**Comment by merks** [comment]
Fortunately that wasn't hard to track down.   The most recent change on that file refactored it to use a try-with 

https://github.com/eclipse-equinox/p2/blob/f5aecaf30d8be20973d17679e4ce86faeb881318/bundles/org.eclipse.equinox.p2.discovery.compatibility/src/org/eclipse/equinox/internal/p2/discovery/compatibility/util/CacheManager.java#L201

But unfortunately it tries to rename that file within the body of the try-with:

https://github.com/eclipse-equinox/p2/blob/f5aecaf30d8be20973d17679e4ce86faeb881318/bundles/org.eclipse.equinox.p2.discovery.compatibility/src/org/eclipse/equinox/internal/p2/discovery/compatibility/util/CacheManager.java#L219

Of course that can never work.

The PR https://github.com/eclipse-equinox/p2/pull/537 fixes this issue allowing the dialog to open:

![image](https://github.com/user-attachments/assets/6a7bac2b-48f4-474a-ac56-39699fd0fb3d)

**Comment by merks** [comment]
The fix will be in the next I-build

**Comment by merks** [comment]
@gloowa 

Thanks for taking the time to report the problem in the right place!  🥇
