### ISSUE TITLE
Deprecate Transport.download(URI, OutputStream, long, IProgressMonitor)

### ISSUE THREAD

**Issue by laeubi** [eclipse-equinox/p2#6]
It seems that the method `org.eclipse.equinox.internal.p2.repository.Transport.download(URI, OutputStream, long, IProgressMonitor)` is actually never called from P2.

As `Transport` is an abstract class I suggest to do the following:

1. mark the method deprecated
2. remove abstract modifier and implement it by throwing `OperationNotSupportedException`.

This would make implementing alternative transport much more easier.

**Comment by merks** [comment]
That will break org.eclipse.oomph.p2.internal.core.CachingTransport likely in a way that makes it impossible to provide an implementation that works with older versions of p2.    I.e., while your new approach new might benefit something new, something old will be broken.

How about if you just throw that exception in your new implementation instead of breaking others?

**Comment by laeubi** [comment]
> That will break org.eclipse.oomph.p2.internal.core.CachingTransport likely

Can you explain this? As mentioned above the method is never called from P2 code anywhere...

**Comment by laeubi** [comment]
@merks I looked at oomph and it seems the method is also there never called with other arguments than `-1` effectively making the mentioned method useless.

I also noticed that oomph uses a lot of reflection magic, I really wonder if it would not make sense to instead adjust P2 to make things more accessible?

**Comment by merks** [comment]
Oomph never calls it, but it does override and delegate and would need to change how it does that.  Maybe that's a simple change and can be done safely in a compatible way...

Yes, it would have been better to have made a great many adjustments in p2, but still mostly the things that needed to be specialized would not be API.  After all, you appear to be wanting to change this so you can implement it differently, even though it's not API.  :-P

**Comment by laeubi** [comment]
I investigate how to improve the caching in P2 itself and simplify the transport handling. But currently all that unused and mixed-concerns stuff make this really hard.

**Comment by akurtakov** [comment]
If you improve P2 caching significantly without API changes - internals can change significantly IMHO. After all the goal should always be to improve user experience not to preserve compatibility in internals (an oxymoron itself) at any price.

**Comment by laeubi** [comment]
For me it is more that implementing partial transfers is rather complicate to get it correct. e.g. a server might even don't support range requests see https://datatracker.ietf.org/doc/html/rfc7233#page-8 even worse, the APi states nothing what could/should happen if ranges are *not* supported (is the caller expected to retry without a range? Should it be handled internally?)

So whenever working with transports I stumble over this method and wonder: Where is it used? And always found: never called at all... But on the other hand as long as it is there it *might* be called one time (and effectively it is called as a delegate method passing -1 in those implementations of ECF + OOMPH).

So technically we can keep this method but I think it is kind of a burden as we never use its intentional use-case (continue partial download) most probably because P2 has no good way to handle that case anyways...

**Comment by vogella** [comment]
@merks why would a default implementation and deprecation break Oomph?

**Comment by laeubi** [comment]
BTW maybe this would be more suitable for a discussion see #4  ...

**Comment by merks** [comment]
@laeubi 

I agree it appears to somewhat of a questionable burden given it's not actually used.

@vogella 

The devil is in the details because this issue only talks about Transport.download and says nothing about how org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport will be changed, though no doubt there will be changes there, and if I delegate to a method that throws an exception, of course that's not going to work.  I'm just making worst case assumptions.

In the end, there is not so much context here, but rather snips of context-free potential changes...

**Comment by merks** [comment]
> If you improve P2 caching significantly without API changes - internals can change significantly IMHO. After all the goal should always be to improve user experience not to preserve compatibility in internals (an oxymoron itself) at any price.

Is there room for shades of gray, or is there really only the polarized extreme choices of black or white?  After all, p2 has done a very poor job of providing APIs before the designers went AWOL.  In addition, Oomph has done a lot to provide improved user experience, including improved caching which is already experienced in all the EPP products.

**Comment by akurtakov** [comment]
@merks Install a plugin on e.g. VSCode and do the same on Eclipse to see the speed difference. I'm not saying this issue itself would improve things to even be noticeable what I say is that we should not shoot things down from the start (e.g. "this would break down.." is not even smth you are sure of as this is yet a discussion) as that leads to getting so much behind competition and the gap widening.

**Comment by laeubi** [comment]
> Is there room for shades of gray, or is there really only the polarized extreme choices of black or white?

I don't see a problem of having gray-zones. I just concerned how we ever proceed here. For me it is really confusing that P2, given its importance, is considered a dead-end where everyone is hacking around its issues or limitations. Tycho has its hacks, oomph has its hack both relying on internal API ... and because of this we can't proceed any further as no one likes to actually change something.

> Oomph has done a lot to provide improved user experience, including improved caching

I think one good thing would be to decide if certain parts of this improvements can't be feed back into P2 again? But if we really want to improve things, I think a major redesign is required, there is just a complete mangling of responsibility and a very bad separation of concerns in P2. And that why its hard to even make small improvements without getting complete of track because everything is interrelated.

Just for the Transport part, there are retries handled in the transport, (mirror) retries handled all over the place on different parts of P2, status code guessing root causes and then deep dependency on ECF as well that has its own complexity and a complexity crazy way of performing authenticate nailed to http-basic-auth. But all this is essentially wasted efforts as we still do not support the very basics of http-caching, even worse, we actually *disable* caching because of some bad servers and so on...

So effectively we do a lot of work performing the job in a bad way :-)

**Comment by mickaelistria** [comment]
I don't get how what's proposed by @laeubi in initial comment coupled by the `default` flag suggested by @vogella in https://github.com/eclipse-equinox/p2/issues/6#issuecomment-1074833869 is controversial. It seems like backward-compatible API simplification.
Unless I'm missing something, I think best thing to do now is for @laeubi (or anyone else) to submit a patch implementing the suggestions and let @merks verify it doesn't break Oomph, and merge upon expected general happiness.

**Comment by laeubi** [comment]
> and let @merks verify it doesn't break Oomph

Just wondering: Would ti be possible to have a job that builds p2 + oomph together to prevent manual verification?

**Comment by vogella** [comment]
> The devil is in the details because this issue only talks about Transport.download and says nothing about how org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport will be changed, though no doubt there will be changes there, and if I delegate to a method that throws an exception, of course that's not going to work. I'm just making worst case assumptions.
> 
> In the end, there is not so much context here, but rather snips of context-free potential changes...

Lets raise such concerns in the code review, of course issues are hard to judge without the real change.

I have to second @akurtakov for the comparison code vs. Eclispe, Eclipse installation feels ridiculous slow (both Marketplace and p2 installation dialog) compared to VsCode extension installation.

**Comment by laeubi** [comment]
> @merks Install a plugin on e.g. VSCode and do the same on Eclipse to see the speed difference.

One downside for sure is that P2 has deep hierarchies to load, but even worse the eclipse servers are also don't allow efficient caching of data I opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1039

**Comment by vogella** [comment]
@laeubi do you want to send a PR for the deprecation? Maybe you can also mark it for deletion (will take at least 3 years to be deleted and might be longer if people still rely on it).

**Comment by laeubi** [comment]
@vogella see https://github.com/eclipse-equinox/p2/pull/42
