### ISSUE TITLE
Retire org.eclipse.equinox.p2.rcp.feature feature?

### ISSUE THREAD

**Issue by vogella** [eclipse-equinox/p2#86]
I have never used the org.eclipse.equinox.p2.rcp.feature with my RCP clients. 

Do we use this feature in your SDK? If not I suggest to retire it, clients can easily add the 5 plug-ins  and 1 feature to their own feature and we would have one feature version less to increase every time we change something in p2 UI.

**Comment by vogella** [comment]
cc @merks @akurtakov @laeubi

**Comment by merks** [comment]
This is the standard way of including it in a product and of my several customer products use it as is the case here:

/org.eclipse.platform.releng.tychoeclipsebuilder/equinox-sdk/equinox-sdk.product

So please no do not retire it.
