### ISSUE TITLE
Failure to restart after update to new Eclipse Version

### ISSUE THREAD

**Issue by wimjongman** [eclipse-equinox/p2#90]
Our Eclipse-based application updates automatically to the latest Eclipse versions. However, when restarting after  "Do you want to restart" we almost always get an error. 

Starting manually again is successful.

Attached is a clean log of this failed restart.
[1655371883857.bak_0.log](https://github.com/eclipse-equinox/p2/files/8917632/1655371883857.bak_0.log)
[1655371883857.log](https://github.com/eclipse-equinox/p2/files/8917633/1655371883857.log)

**Comment by tjwatson** [comment]
> Actually all bundles you configure before or at the same start level are added to the config.ini and simpleconfigurator should most probably know that, I'm a bit curious that so many "hacks" are required to support simpleconfigurator, why does the refresh not happen when the application is already down?

WMMV, but I've yet to find a project that has no hacks at all in its bootstrap code and simpleconfigurator is by all means bootstrap code.

Why doesn't simpleconfigurator do its update when the application is already down?  That likely is a long conversation.  It is not clear what you mean by application, is that the Java process itself?  Is that the Equinox Framework, or is that the Eclipse notion of "Application"?  Like I said, simpleconfigurator will work best when it is thought of as bootstrap code.  It works best when it is running without anything else running to interfere.

**Comment by laeubi** [comment]
> Why doesn't simpleconfigurator do its update when the application is already down?

No I don't mean simplple configurator should do anything here but

https://github.com/eclipse-equinox/equinox/tree/master/bundles/org.eclipse.equinox.app

there is a request to `EXIT_RESTART` the app and that would be the place where a refresh could/should happen for any pending, as at this state the application is shut down to its lowest level (as far as I found while debugging this once).

So then when Simpleconfigurator becomes active everything is refreshed (including any fragments).
