### ISSUE TITLE
Comparator errors in 4.25 I-Build: I20220616-0910

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-equinox/p2#92]
Here is the artifacts comparison report https://download.eclipse.org/eclipse/downloads/drops4/I20220616-0910/buildlogs/comparatorlogs/buildtimeComparatorUnanticipated.log.txt

And comparisons zip file
[artifactcomparisons.zip](https://github.com/eclipse-equinox/p2/files/8920904/artifactcomparisons.zip)

**Comment by merks** [comment]
@sravanlakkimsetti  Is this issue still relevant that p2 needs to take some action?

**Comment by sravanlakkimsetti** [comment]
This is fixed via https://github.com/eclipse-jdt/eclipse.jdt.core/issues/147
