### ISSUE TITLE
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase

### ISSUE THREAD

**Issue by SatishChGit** [eclipse-equinox/p2#95]
tycho-p2-director-plugin:2.7.0:materialize-products (materialize-products) @ products throwing error 
Installation failed.
An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
        session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
        NullPointerException
        Caused by:
        java.lang.NullPointerException

We have a product implemented on eclipse equinox framework, emf and dtp framework base. We are using eclipse https://download.eclipse.org/releases/2022-03/202203161000 repository to download eclipse plugins and features. It was working successfully previously but all of sudden it is getting failed. Attached log file with error log.
[Eclipse202203Error.txt](https://github.com/eclipse-equinox/p2/files/9007556/Eclipse202203Error.txt)

**Comment by mickaelistria** [comment]
Can you please try with Tycho 3.0.0-SNAPSHOT?

**Comment by merks** [comment]
Or try 2.7.3.  

There is no code at this line that could produce an NPE:

https://github.com/eclipse-equinox/p2/blob/dd17c88905ee31eb519ab67f4b14c6f8de9ddc7d/bundles/org.eclipse.equinox.p2.engine/src/org/eclipse/equinox/internal/p2/engine/phases/CertificateChecker.java#L292

So you need a version of Tycho that is based on the 2022-03 release of the platform/p2.

**Comment by SatishChGit** [comment]
I tried to use 2.7.3. There are couple of plugins which doesnt have src folder and this tycho plugin is giving error as below. With previous versions of tycho, it doesn't raise the issue. 
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:2.7.3:package-plugin (default-package-plugin) on project com.teradata.datatools.asterdata.jdbc: Execution default-package-plugin of goal org.eclipse.tycho:tycho-packaging-plugin:2.7.3:package-plugin failed: basedir /root/studio/TychoBuild/build/bundles/com.teradata.datatools.asterdata.jdbc/target/classes does not exist 

![image](https://user-images.githubusercontent.com/23031170/176427410-7eaf9a2f-f9f3-4d7d-a4fa-db4c4e9a00a5.png)

**Comment by merks** [comment]
This is an issue best discussed or reported for Tycho.

https://github.com/eclipse/tycho

**Comment by SatishChGit** [comment]
Okay sure thank you.
