### ISSUE TITLE
Revert installation fails due to missing source bundles

### ISSUE THREAD

**Issue by vogella** [eclipse-equinox/p2#96]
Trying to downgrade Eclipse Build id: I20220629-0320 to the  Eclipse SDK 4.25.0.I20220620-1050 download 

![image](https://user-images.githubusercontent.com/139910/176428925-96f2a6e8-7601-4424-930d-5bf38f878ba6.png)

fails with the following error:

An error occurred while collecting items to be installed
session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.core.resources.source,3.18.0.v20220616-1205
No repository found containing: osgi.bundle,org.eclipse.core.runtime.source,3.25.100.v20220613-1008
No repository found containing: osgi.bundle,org.eclipse.debug.core.source,3.20.0.v20220618-1551
No repository found containing: osgi.bundle,org.eclipse.debug.ui.source,3.16.200.v20220618-1805
No repository found containing: org.eclipse.update.feature,org.eclipse.e4.rcp,4.25.0.v20220620-1437
No repository found containing: org.eclipse.update.feature,org.eclipse.e4.rcp.source,4.25.0.v20220620-1437
No repository found containing: osgi.bundle,org.eclipse.e4.ui.css.swt.source,0.14.600.v20220613-1243
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.core.feature,1.6.1500.v20220618-1214
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.core.feature.source,1.6.1500.v20220618-1214
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.extras.feature,1.4.1700.v20220618-1214
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.extras.feature.source,1.4.1700.v20220618-1214
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.rcp.feature,1.4.1700.v20220618-1214
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.rcp.feature.source,1.4.1700.v20220618-1214
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.user.ui,2.4.1700.v20220618-1214
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.user.ui.source,2.4.1700.v20220618-1214
No repository found containing: osgi.bundle,org.eclipse.equinox.preferences.source,3.10.100.v20220615-0641
No repository found containing: osgi.bundle,org.eclipse.help.base.source,4.3.800.v20220620-1050
No repository found containing: org.eclipse.update.feature,org.eclipse.help,2.3.1100.v20220620-1050
No repository found containing: org.eclipse.update.feature,org.eclipse.help.source,2.3.1100.v20220620-1050
No repository found containing: osgi.bundle,org.eclipse.help.webapp.source,3.10.800.v20220619-1918
No repository found containing: osgi.bundle,org.eclipse.jdt.core.manipulation.source,1.16.200.v20220616-2128
No repository found containing: osgi.bundle,org.eclipse.jdt.core.source,3.30.100.v20220610-0933
No repository found containing: org.eclipse.update.feature,org.eclipse.jdt,3.18.1300.v20220620-1050
No repository found containing: osgi.bundle,org.eclipse.jdt.launching.source,3.19.600.v20220616-0716
No repository found containing: org.eclipse.update.feature,org.eclipse.jdt.source,3.18.1300.v20220620-1050
No repository found containing: osgi.bundle,org.eclipse.jdt.ui.source,3.27.0.v20220610-0607
No repository found containing: osgi.bundle,org.eclipse.osgi.source,3.18.100.v20220620-1437
No repository found containing: osgi.bundle,org.eclipse.pde.core.source,3.15.300.v20220608-1017
No repository found containing: org.eclipse.update.feature,org.eclipse.pde,3.14.1300.v20220620-1050
No repository found containing: osgi.bundle,org.eclipse.pde.launching.source,3.10.100.v20220608-1017
No repository found containing: org.eclipse.update.feature,org.eclipse.pde.source,3.14.1300.v20220620-1050
No repository found containing: osgi.bundle,org.eclipse.pde.ui.source,3.13.600.v20220617-0655
No repository found containing: org.eclipse.update.feature,org.eclipse.platform,4.25.0.v20220620-1437
No repository found containing: osgi.bundle,org.eclipse.platform.source,4.25.0.v20220620-1050
No repository found containing: org.eclipse.update.feature,org.eclipse.platform.source,4.25.0.v20220620-1437
No repository found containing: org.eclipse.update.feature,org.eclipse.rcp,4.25.0.v20220620-1437
No repository found containing: org.eclipse.update.feature,org.eclipse.rcp.source,4.25.0.v20220620-1437
No repository found containing: org.eclipse.update.feature,org.eclipse.sdk,4.25.0.v20220620-1437
No repository found containing: osgi.bundle,org.eclipse.swt.win32.win32.x86_64.source,3.121.0.v20220614-2203
No repository found containing: osgi.bundle,org.eclipse.ui.ide.application.source,1.4.500.v20220614-0941
No repository found containing: osgi.bundle,org.eclipse.ui.workbench.source,3.125.200.v20220617-1016

**Comment by merks** [comment]
Those are no longer in the composite, e.g., 

![image](https://user-images.githubusercontent.com/208716/176431641-100e77d8-822a-40d7-afd6-8ba6f891232c.png)

Recall the discussion on cross projects about the release train composite having multiple versions of bundles and the reason for that being support for rollback?

https://www.eclipse.org/lists/cross-project-issues-dev/msg19228.html

Also, there was recently a discussion to reduce the number of repos in the I build composite to 2 so that has an impact on rollback support as well.  @sravanlakkimsetti  FYI

So this is not a problem that can be fixed by p2.  (Installing with Oomph with it's shared bundle pool would likely not have this problem because the artifacts would remain in the pool until you manually garbage collected them.)

**Comment by merks** [comment]
@akurtakov @jonahgraham 

Note that not having rollback support can be noticeable.

**Comment by sravanlakkimsetti** [comment]
With 4 repos in I-build repo also will not be able to help here. 
@vogella Can you try adding https://download.eclipse.org/eclipse/updates/4.25-I-builds/I20220620-1050 to your repo list and try rollback. this might help

**Comment by merks** [comment]
Yes, of course at some point the builds are too old.   And of course few "real end users" are updating to nightly builds or to SimRel milestone builds so very few are likely impacted but fewer builds in a composite...

**Comment by vogella** [comment]
So the issue is only that the temp repo is gone? No worries in this case.... I can just download an older version.

**Comment by merks** [comment]
Yes, if the bundles needed for the revert are no longer in the installation's artifact pool (which is generally garbage collected eagerly on startup) and no longer in any available repository, then you will get an error like this.

**Comment by jonahgraham** [comment]
> So this is not a problem that can be fixed by p2.

Not that I am advocating spending the time/effort on this. But it could be fixed on p2 if p2 kept track where it installed from, so when doing the rollback it would know where to find them. 

However I would argue (fruitlessly, because again I am not advocating for a change because I don't think it is worth it) that if p2 has a rollback available to users it should not garbage collect those items.

But anyway, I am nowhere near enough knowledgeable about p2 to know if what I said is even correct.

---

On the 2022-09 M2 I have this in my [endgame plan](https://hackmd.io/@jonahgraham/eclipse-epp-release-process):

- [ ] In 2022-09 stop making p2 repos composites of all milestones - see https://wiki.eclipse.org/Planning_Council/2022-06-01
    - [ ] Test rollback from M2 to M1, and document what it takes to work (best guess is just manually adding in p2 repos)

**Comment by merks** [comment]
Indeed, in general such a problem cannot be fixed other than by not **ever** garbage collecting.  Update sites can and do disappear.   E.g., EMF's nightly build composite has at most 5 sites and one site will be deleted every time there is a new nightly build.  (Note that the installer uses a shared bundle pool and it does no automatic garbage collection, so I believe that already solves this problem.)

If at least p2 didn't immediately garbage collect on startup, one could roll back right after installing an update after noticing that it works poorly...

In terms of endgame plans, I think it's much more important that a user updating from 2022-06 to 2022-09 should be able to rollback than someone updating from M1 to M2 should be able to rollback, given that the former involves millions of users while the latter is perhaps a few hundred people.  I expect the former works fine while the latter is likely problematic.
