### ISSUE TITLE
The org.eclipse.equinox.p2.core bundles released after September 2021, requires bouncy castle 1.65.0 version

### ISSUE THREAD

**Issue by wasuradananjith** [eclipse-equinox/p2#98]
The org.eclipse.equinox.p2.core bundles [1] released after September 2021, requires bouncy castle 1.65.0 version which as added by [2].
For instance, the latest org.eclipse.equinox.p2.core bundle's (2.9.100) MANIFEST.MF contains this requirement as shown below.

Import-Package: **org.bouncycastle.bcpg;version="1.65.0",org.bouncycastle.
 openpgp;version="1.65.0"**,org.eclipse.core.runtime;common=split;version=
 "[3.5.0,4.0.0)",

This particular bouncy castle version has security vulnerabilities with high severities as well [3], thus we cannot use this bouncy castle version in production.

Is it possible to release a new org.eclipse.equinox.p2.core bundle that has the support for the latest bouncy castle version? @mickaelistria Any possibility of this?

[1] https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.equinox.p2.core
[2] https://github.com/eclipse-equinox/p2/commit/45af7098437c45a46e7637d9aeb0177ca998e209
[3] https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on

**Comment by laeubi** [comment]
> This particular bouncy castle version has security vulnerabilities with high severities

Can you explain which of those are relevant for P2 (that only uses BC to validate PGP keys)

> Is it possible to release a new org.eclipse.equinox.p2.core bundle that has the support for the latest bouncy castle version?

You can simply deploy a never BC version if you like, the package imports are just lower bounds.

**Comment by merks** [comment]
As mentioned, that's just a lower bound. You'll see that the most recent release is actually using version 1.7.0:

https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/eclipse/updates/4.24/R-4.24-202206070700/index.html

https://download.eclipse.org/oomph/archive/reports/download.eclipse.org/eclipse/updates/4.24/R-4.24-202206070700/index/org.bouncycastle.bcprov_1.70.0.v20220507-1208.html

So I don't think here is anything to do here...

**Comment by mickaelistria** [comment]
@merks is right. The version here is a compatibility bound, not a specific requirement. A newer bouncycastle has been actually shipped by default in latest and upcoming release.

**Comment by akurtakov** [comment]
@wasuradananjith I think it's fine if we raise our min requirement to not include bc with CVEs. As 1.66 has some too would you please provide a PR bumping it to 1.67 ?
